### ISSUE TITLE
New View

### ISSUE THREAD

**Issue by maqf12** [basnijholt/lovelace-ios-dark-mode-theme#55] opened 2020-06-26 20:06 UTC
Hi
When i add a new view bg color dosen´t follow ? How to add this. Works flawless in the first view

**Comment by basnijholt** [comment] 2020-06-30 07:30
I am not sure what you mean. Can you try to reword your problem and/or add some screenshots?

**Comment by basnijholt** [comment] 2020-09-24 08:52
Closing because it's not clear what the problem is.

**Closed by basnijholt** 2020-09-24 08:52 UTC
